"""Error was at these stage

Revision ID: 4263f6e7acdc
Revises: 444493313651
Create Date: 2023-08-08 13:18:53.832771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4263f6e7acdc'
down_revision = '444493313651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_exercises', type_='foreignkey')
    op.create_foreign_key(None, 'training_exercises', 'trainings', ['training_id'], ['training_id'], ondelete='CASCADE')
    op.drop_column('training_exercises', 'id')
    op.add_column('trainings', sa.Column('training_id', sa.Integer(), nullable=False))
    op.add_column('trainings', sa.Column('date', sa.DateTime(), nullable=False))
    op.drop_column('trainings', 'creation_date')
    op.drop_column('trainings', 'finishing_date')
    op.drop_column('trainings', 'finished')
    op.drop_column('trainings', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('id', sa.INTEGER(), nullable=False))
    op.add_column('trainings', sa.Column('finished', sa.BOOLEAN(), nullable=True))
    op.add_column('trainings', sa.Column('finishing_date', sa.DATETIME(), nullable=True))
    op.add_column('trainings', sa.Column('creation_date', sa.DATETIME(), nullable=True))
    op.drop_column('trainings', 'date')
    op.drop_column('trainings', 'training_id')
    op.add_column('training_exercises', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'training_exercises', type_='foreignkey')
    op.create_foreign_key(None, 'training_exercises', 'trainings', ['training_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
