"""new training(empty)

Revision ID: 78fcdab91e71
Revises: 8a099b8c2bc8
Create Date: 2023-07-28 12:52:22.757157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78fcdab91e71'
down_revision = '8a099b8c2bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainings',
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('training_id')
    )
    op.create_table('training_exercises',
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.exercise_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.training_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('training_id', 'exercise_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_exercises')
    op.drop_table('trainings')
    # ### end Alembic commands ###
