"""location_filter changed to filters in exercise model

Revision ID: ee08649347ad
Revises: d7cda8d0f36f
Create Date: 2023-08-03 13:18:13.466815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ee08649347ad'
down_revision = 'd7cda8d0f36f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('filters', sa.JSON(), nullable=True))
    op.drop_column('exercises', 'location_filter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('location_filter', sqlite.JSON(), nullable=True))
    op.drop_column('exercises', 'filters')
    # ### end Alembic commands ###
